### PR TITLE
refac/jira config

### PR DESCRIPTION
**Pull request by mikhaili**
1. package.json
add developments scripts
move eslint to dev dependencies
    "dev": "node bin/jira.js",  -> run development version of jira
    "global": "npm i -g && jira", -> install current project on system
    "clean": "rimraf -rf ./.jira-cli", -> remove config from project directory
    "clean:global": "rm -rf ~/.jira-cli"
2. config.js
config file management moved to config file (load, save, loadInitialConfig) removed dependencies from auth file

default_config renamed to initial_config

3. auth.js
removed dependencies on config file (path to the file, save, load)
4. settings.js contain base project setting home_directory, 
configfile info: file name , directory name

### CODE REVIEW

**Comment by rluvaton** [comment]
@danshumaker Is this gonna be merged soon? because it contains some breaking changes

**Comment by danshumaker** [comment]
Hi @rluvaton and @mikhaili , unfortunately I merged in some other changes not in chronological order. So these changes for this PR cause all kinds of conflicts. I was going to ask @mikhaili to re-do & re-submit the changes with the new code and version.  Locally on my dev machine I'm right in the middle of resolving those conflicts but I keep getting interrupted.  @mikhaili Any chance you could work on this?

**Comment by mikhaili** [comment]
> Hi @rluvaton and @mikhaili , unfortunately I merged in some other changes not in chronological order. So these changes for this PR cause all kinds of conflicts. I was going to ask @mikhaili to re-do & re-submit the changes with the new code and version. Locally on my dev machine I'm right in the middle of resolving those conflicts but I keep getting interrupted. @mikhaili Any chance you could work on this?

Hey maybe I can split that PR to smaller ones, I will close it if it ok? and reopen later, @rluvaton do u need my changes?

**Comment by mikhaili** [comment]
out of date

**Comment by mikhaili** [comment]
@rluvaton 

> @danshumaker Is this gonna be merged soon? because I want to contribute but it contains some meaningful changes...

@rluvaton hey how are u?
You are welcome to add your code,  just can u open the issue and describe feature you going to add?

**Comment by rluvaton** [comment]
> @rluvaton 
> 
> 
> 
> > @danshumaker Is this gonna be merged soon? because I want to contribute but it contains some meaningful changes...
> 
> 
> 
> @rluvaton hey how are u?
> 
> You are welcome to add your code,  just can u open the issue and describe feature you going to add? 

Of course, I didn't want to make changes because it will have large merge conflicts

**Pull request closed without merging**
